spring:
  datasource:
    url:      ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update





aws:
  region: us-east-1
  s3:
    bucket: medalmp3-audiostream
